modLoader="javafml"
loaderVersion="[36,)"
license="Apple Public Source License version 2.0 (APSL)"

[[mods]]
modId="jsrp"
version="1.0.0"
displayName="jsrp_mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Moryn"

[[dependencies.jsrp]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




